// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Post : BaseEntity
{
    public string? Title { get; set; }
    public string? Description { get; set; }
    public string? BuildingName { get; set; }
    public List<string>? ImageUrl { get; set; }
    public decimal? Price { get; set; }
    public string? Address { get; set; }
    public string? PropertyType { get; set; }
    public string? ApartmentNumber { get; set; }
    public string? Block { get; set; }
    public string? Floor { get; set; }
    public string? ApartmentType { get; set; }
    public string? Bedrooms { get; set; }
    public string? Bathrooms { get; set; }
    public string? LegalDocument { get; set; }
    public string? FurnitureCondition { get; set; }
    public string? Area { get; set; }
    public decimal? Deposit { get; set; }
    public Guid? UserId { get; set; }
    public virtual User User { get; set; }
}

