// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class Post : BaseEntity
{
    public Guid RoomId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public decimal Price { get; set; }

    public string Phone { get; set; }

    public string SocialAccount { get; set; }

    

    public virtual Room Room { get; set; }
}