// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessLayer.Models;

public partial class User : BaseEntity
{
    public string? Email { get; set; }
    public string Username { get; set; }

    public string FullName { get; set; }
    public string Password { get; set; }
    public string PhoneNumber { get; set; }

    public string? Gender { get; set; }

    public DateTime? Dob { get; set; }

    public string? Address { get; set; }

    public Guid RoleId { get; set; }

    public virtual Role Role { get; set; }
    public virtual ICollection<Post> Posts { get; set; }
    public virtual ICollection<Transaction> Transactions { get; set; }
}


