// <auto-generated />
using System;
using DataAccessLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(HomeHuntContext))]
    [Migration("20241021170013_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApartmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bathrooms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bedrooms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FurnitureCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("post_id_primary");

                    b.HasIndex("UserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("role_id_primary");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f82ec39-63e6-4cd4-95d2-091a656ae301"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("user_id_primary");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("user_email_unique")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("user_Username_unique");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ca56bed-13ca-4067-8a72-551bcd35318c"),
                            FullName = "Admin 1",
                            Password = "5rH4V4vMfua+KRkWe+JH9zS7FuO/2XBj/5LnSPQjaUh/gvXW",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("8f82ec39-63e6-4cd4-95d2-091a656ae301"),
                            Username = "Admin1"
                        },
                        new
                        {
                            Id = new Guid("98688ba0-3003-4aa5-8bd2-93ced308e027"),
                            FullName = "Admin 2",
                            Password = "Wd/usMCgquZ83NokCzRyGLOd0UB7qb9El9Q69/T4syeI0qVU",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("8f82ec39-63e6-4cd4-95d2-091a656ae301"),
                            Username = "Admin2"
                        },
                        new
                        {
                            Id = new Guid("a89ba03b-fdb1-4bca-a13a-f6d3b3e42171"),
                            FullName = "Customer 1",
                            Password = "HUmMGn5qNqCQkUxU+szcYqpgJTmJ898ZlLVGLtixgMcf79qb",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer1"
                        },
                        new
                        {
                            Id = new Guid("a35a1a07-ec1e-4070-ab82-001b52a568d9"),
                            FullName = "Customer 2",
                            Password = "HYlJFGqPzpjuK2jJsMZTVEwoufNNBUQmGDNQ8YAz1E8MFHkj",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer2"
                        },
                        new
                        {
                            Id = new Guid("9496aab7-d66c-4001-9cf9-d3c65713970e"),
                            FullName = "Customer 3",
                            Password = "y+cSla+oVnHKEcihX9uUfva6cCrnVTndoWdRsuI0zyKEQJWO",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer3"
                        },
                        new
                        {
                            Id = new Guid("1d06ca65-ad44-4bff-b7a7-1a4039763880"),
                            FullName = "Customer 4",
                            Password = "iqyDjmKTPEyvtkFj5DVhoByYebFYWHy7HnJISjfiORG0vpkW",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer4"
                        },
                        new
                        {
                            Id = new Guid("cf8f0a56-d072-4fe7-af8a-56953e4df553"),
                            FullName = "Customer 5",
                            Password = "QCAW06OGrNuaTsueJu43rGw2nLBWUdOnCUGyi5c3Bv9I5jnl",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer5"
                        },
                        new
                        {
                            Id = new Guid("df936c1d-4ebf-435a-8f80-41110f31a071"),
                            FullName = "Customer 6",
                            Password = "ERA/vOyWxAmpBJMAfQ+ACSSZ7jFn9ZDpTM/c0FGLYni7Ng6p",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer6"
                        },
                        new
                        {
                            Id = new Guid("2ead1812-5078-4262-8f22-9b00b0a5b94f"),
                            FullName = "Customer 7",
                            Password = "3rLfzTzeohKaBDPKOXEPy1qRWGQPcLufWtjaMBZYBe+8IoMQ",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer7"
                        },
                        new
                        {
                            Id = new Guid("02225135-f486-4755-ae8c-c44a7562bb4c"),
                            FullName = "Customer 8",
                            Password = "aI/pLjTOpKNuXbOfbTEoD7hFwCaN0KQC30rWyKUl/SwQsPU0",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer8"
                        },
                        new
                        {
                            Id = new Guid("8d0512d9-4934-4a59-afc9-7ca829610867"),
                            FullName = "Customer 9",
                            Password = "Km/Zr9HQnHPl1AU2K6Itlea0GZ2eMp0Qz/Nr9J3yyBfZtZKD",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer9"
                        },
                        new
                        {
                            Id = new Guid("8096e6cd-b480-4003-bbf2-cbf72a273012"),
                            FullName = "Customer 10",
                            Password = "RVBpk+binuzvGy39fcEDyRB9D6CBlnoQYzE6KMG3BoYcw+yp",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer10"
                        },
                        new
                        {
                            Id = new Guid("dd9fb8a7-4153-4fa6-b6b6-ab6c9df0ca77"),
                            FullName = "Customer 11",
                            Password = "cax3dyvzW9B7jWQSKJ4q+ulPK4DeJLJrB9e0PBWZKGf6XH8r",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer11"
                        },
                        new
                        {
                            Id = new Guid("b7074ced-a177-49f5-81ee-a57f96b2091d"),
                            FullName = "Customer 12",
                            Password = "ng16blBP82WpSucSaOqEv2mg5ruHJox/m/RhWzQjvwoOW+1f",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer12"
                        },
                        new
                        {
                            Id = new Guid("6d4efbf5-57e2-4521-b0cd-02b6423391de"),
                            FullName = "Customer 13",
                            Password = "TqKK78dCYQgD4I2np48J+CoCqvn00FKWHawLuz3Y+6M9bVNJ",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer13"
                        },
                        new
                        {
                            Id = new Guid("65d9946c-9479-47d8-a9f3-ad3c9f8de268"),
                            FullName = "Customer 14",
                            Password = "Fm9aQSJbTFAnTocArxCShj0ArSS+GldTSzF/bIoBtgv6u6Os",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer14"
                        },
                        new
                        {
                            Id = new Guid("d28029b2-f642-49f0-802b-40cc1d894fd5"),
                            FullName = "Customer 15",
                            Password = "0jSJy3Ll3dp1Y4ienuDQLQwRVklaVv5E29pdzfSqgivTn8l5",
                            PhoneNumber = "123456789",
                            RoleId = new Guid("bcadf39b-13b8-4958-8472-61f4c993fbe5"),
                            Username = "Customer15"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Post", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("post_userid_foreign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("user_roleid_foreign");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
